### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by Aj3douglas** [paypal/Payouts-Java-SDK#10]
In the Readme of this repo an example is shown

` CreatePayoutsRequest request = CreatePayoutRequest()
                .senderBatchHeader(new SenderBatchHeader()
                        .senderBatchId("Test_sdk_" + RandomStringUtils.randomAlphanumeric(7))
                        .emailMessage("SDK payouts test txn")
                        .emailSubject("This is a test transaction from SDK")
                        .note("Enjoy your Payout!!")
                        .recipientType("EMAIL"))
                .items(items);`

In the payouts Java SDK, there is no class named `CreatePayoutsRequest`, however there is a `CreatePayoutRequest`. If CreatePayoutsRequest is substituted for that, on this line 
`HttpResponse<CreatePayoutResponse> response = Credentials.client.execute(request);`
we come into a TypeMismatch error, 
Required:
HttpRequest<(???..???)>!
Found:
CreatePayoutRequest!

It is unclear the correct way to do this, as it seems the documentation is outdated.

**Comment by aninja8** [comment]
@Aj3douglas It is a typo in the readme document. Will fix it. Meanwhile, you can check out the sample here: https://github.com/paypal/Payouts-Java-SDK/blob/master/payouts-sdk-sample/src/main/java/com/paypal/CreatePayoutsBatch.java

**Comment by hadjiski** [comment]
@aninja8 since this seems to be not picked up any time soon, I created a [PR](https://github.com/paypal/Payouts-Java-SDK/pull/11), feel free to merge it

**Comment by rajkumarpalani** [comment]
Thanks for the PR @hadjiski . Closing as the PR is merged
