### ISSUE TITLE
Why does CreatePayoutResponse need to hold a collection of errors?

### ISSUE THREAD

**Issue by hadjiski** [paypal/Payouts-Java-SDK#13]
When I use the API (`CreatePayoutRequest`) whenever I have an error like insufficient funds, a `HttpException` is thrown and inside the message field I have the json representation of a `PayoutError`, but when the payout call is successful, then my `CreatePayoutResponse`'s errors collection is of course empty or null.

What is the use case of a valid response object with http status code of 2xx and having errors collection not empty?

**Comment by rajkumarpalani** [comment]
@hadjiski the `PayoutError` as part of `CreatePayoutRequest` will be removed in an upcoming minor version  release of SDK
