### ISSUE TITLE
Payout response in a single request

### ISSUE THREAD

**Issue by RamyaAshika** [paypal/Payouts-Java-SDK#7]
Hi,
  I'm sending a batch of transaction. If one transaction is failed I'm getting response like this
{
    "name": "VALIDATION_ERROR",
    "message": "Invalid request - see details",
    "debug_id": "53d95c3d17ae5",
    "information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors",
    "details": [
        {
            "field": "items[1].receiver",
            "location": "body",
            "issue": "Receiver is invalid or does not match with type"
        },
        {
            "field": "items[3].receiver",
            "location": "body",
            "issue": "Receiver is invalid or does not match with type"
        }
    ],
    "links": []
}
but I want to get the response of successfull also in a batch. Is it possible to get the batch id for failed and success transanction also in a batch?

**Comment by rajkumarpalani** [comment]
@RamyaAshika Payouts API rejects a request when there is validation failures in any of the Payout item. Only if the request is syntactically correct, it will be accepted for processing.
When there is a Validation failure the errors are provided(on fields where it didn't match the validation) to the caller so that it can be corrected
Hope this helps

**Comment by RamyaAshika** [comment]
Ya yes, its giving me the error in detailed response but what about the other transaction details in a payout?  @rajkumarpalani

**Comment by rajkumarpalani** [comment]
When you get this response the request is not accepted for processing and money won't be debited. Can you please check if the debit is due to other activity

**Comment by RamyaAshika** [comment]
Ok but I have tested twice, it was happened that why I raised issue so let me check again. and let you know on this. @rajkumarpalani

**Comment by Roshak94** [comment]
> name": "VALIDATION_ERROR",
> "message": "Invalid request - see details",
> "debug_id": "53d95c3d17ae5",
> "information_link

 "id":"rb5wq1dczvbm",
      "name":"Some Component",
      "status":"operational

**Comment by rajkumarpalani** [comment]
@RamyaAshika closing as this doesn't seem valid
